version: 2

models:
  - name: dim_ip_location
    description: "table ip_location"
    config:
      materialized: table
      schema: dataset_glamira
    columns:
      - name: location_key
        data_tests:
          - unique
          - not_null
      - name: city
        data_tests:
          - not_null
      - name: region
        data_tests:
          - not_null
      - name: country_short
        data_tests:
          - not_null
      - name: country_name
        data_tests:
          - not_null
  - name: dim_user
    config:
      materialized: table
      schema: dataset_glamira
    columns:
      - name: user_key
        data_test:
          - unique
          - not_null
      - name: email_address
        data_tests:
          - not_null
  - name: dim_products
    config:
      materialized: table
      schema: dataset_glamira
    columns:
      - name: product_key
      - name: product_name
      - name: category_name
      - name: collection_name
      - name: product_type
      - name: product_gender
  - name: dim_date
    config:
      materialized: table
      schema: dataset_glamira
    columns:
      - name: date_key
        data_tests:
          - unique
          - not_null
      - name: date
      - name: day_of_week
      - name: day_of_month
      - name: day_of_year
      - name: month
      - name: year
  - name: fact_sales_order
    config:
      materialized: table
      schema: dataset_glamira
    columns:
      - name: sales_hash_key
        datatests:
          - unique
          - not_null
      - name: product_key
        datatests:
          - not_null
      - name: user_key
        datatests:
          - not_null
      - name: location_key
        datatests:
          - not_null
      - name: date_key
        datatests:
          - not_null
      - name: order_key
        datatests:
          - not_null
      - name: local_time
        datatests:
          - not_null
      - name: ip_address
        datatests:
          - not_null
      - name: product_price_usd
        data_tests:
          - not_null
      - name: line_total_usd
        data_tests:
          - not_null
      - name: product_currency
        data_tests:
          - not_null
