version: 2

models:
  - name: stg_raw_ip_location
    description: "view ip_location"
    config:
      materialized: "view"
    columns:
      - name: location_key
        data_tests:
          - unique
          - not_null
      - name: city
        data_tests:
          - not_null
      - name: region
        data_tests:
          - not_null
      - name: country_short
        data_tests:
          - not_null
      - name: country_long
        data_tests:
          - not_null
      - name: ip
        data_tests:
          - not_null
  - name: stg_raw_user
    config:
      materialized: "view"
    columns:
      - name: user_key
        data_tests:
          - unique
          - not_null
      - name: device_id
        data_tests:
          - not_null
      - name: email_address
        data_tests:
          - not_null
      - name: user_agent
        data_tests:
          - not_null
  - name: stg_raw_products
    config:
      materialized: view
    columns:
      - name: product_key
        data_test:
          - unique
          - not_null
      - name: product_name
        data_tests:
          - not_null
      - name: product_price
        data_tests:
          - not_null
      - name: category_id
        data_tests:
          - not_null
      - name: category_name
        data_tests:
          - not_null
      - name: collection_id
        data_tests:
          - not_null
      - name: collection_name
        data_tests:
          - not_null
      - name: product_type
        data_tests:
          - not_null
      - name: visible_contents
        data_tests:
          - not_null
      - name: quantity
        data_tests:
          - not_null
      - name: product_status
        data_tests:
          - not_null
  - name: stg_raw_date
    config:
      materialized: view
    columns:
      - name: date_key
        data_test:
          - unique
          - not_null
      - name: date
      - name: day_of_week
      - name: day_of_month
      - name: day_of_year
      - name: month
      - name: year
  - name: stg_fact_sales_order
    config:
      materialized: view
    columns:
      - name: sales_hash_key
        data_test:
          - unique
          - not_null
      - name: product_key
        data_tests:
          - unique
          - not_null
      - name: user_key
        data_tests:
          - unique
          - not_null
      - name: location_key
        data_tests:
          - unique
          - not_null
      - name: date_key
        data_tests:
          - unique
          - not_null
      - name: order_key
        data_tests:
          - unique
          - not_null
      - name: local_time
        data_tests:
          - not_null
      - name: ip_address
        data_tests:
          - not_null
      - name: quantity
        data_tests:
          - not_null
      - name: price
        data_tests:
          - not_null
      # - name: line_total
      #   data_tests:
      #     - not_null
